corpus_df_path: "data/python_selected_files.parquet"
text_col: "content"
title_col: "path"
n_docs: 100
collection_path: "output/python_code_doc_coll_smal.tsv"
additional_cols: ["tasks", "repo_name"]
index_save_path: "output/indices/python_code_index_small"
doc_len: 4096
batch_size: 512
