corpus_df_path: "data/python_files.json"
text_col: "content"
title_col: "name"
collection_path: "output/python_code_50_tasks_doc_coll.tsv"
additional_cols: ["tasks", "repo_name", "path"]
index_save_path: "output/indices/python_code_50_tasks_index"
doc_len: 4096
batch_size: 512
