[project]
name = "hf_util"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jakub 'lambdaofgod' Bartczuk <bartczukkuba@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["linux-64"]

[tasks]
zsl = "python zsl_app.py"

[dependencies]
transformers = "4.38.1.*"
sentencepiece = "0.1.99.*"
pip = "24.0.*"
pytorch = "2.0.1.*"
pytorch-cuda = "11.8.*"
pydantic = "2.6.2.*"
fire = "0.5.0.*"
ipdb = "0.13.13.*"
fastapi = "0.110.0.*"
pyyaml = "6.0.1.*"
uvicorn = "0.27.1.*"
